### ISSUE TITLE
Recommendation: prefer https over ssh

### ISSUE THREAD

**Issue by FilipChalupa** [contember/starter-kits#29]
```diff
-Clone this starter kit (git clone git@github.com:contember/starter-kits.git)
+Clone this starter kit (git clone https://github.com/contember/starter-kits.git)
```

Https is widely more supported.

**Comment by FilipChalupa** [comment]
I have a strong opinion about forcing an unknown package `degit` with only a few weekly downloads just to clone/copy a repo but it's your choice. 🤷

**Comment by jonasNobile** [comment]
Degit allows to copy only folder in a repo, which is relevant for starter kits. 

Also, degit is not totally unknown package. It has over 60k weekly downloads and author of the package is well-known in community.
