### ISSUE TITLE
Can't create a new migration with fresh clone of headless-cms

### ISSUE THREAD

**Issue by FilipChalupa** [contember/starter-kits#37]
There is some kind of `eventLog` problem.

![image](https://user-images.githubusercontent.com/1045362/180188149-d45c44dd-61e2-42e7-8772-2d19629858cf.png)

**Comment by FilipChalupa** [comment]
Updating dependencies did the trick for me.

![image](https://user-images.githubusercontent.com/1045362/180190126-0f64713e-811f-4371-a5cb-8de711f420b7.png)

![image](https://user-images.githubusercontent.com/1045362/180190150-6641a86d-77db-4555-95bc-b20a5f66b3ac.png)

**Comment by honzasladek** [comment]
@FilipChalupa We've published new versions of Starter kits with access control decorators and more and fixed this issue.
